spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/people_and_organizations
    username: people_and_organizations
    password: people_and_organizations
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: PeopleAndOrganizationsServiceEndpointRest
    admin:
      enabled: true

