spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/people_and_organizations
    username: people_and_organizations-database
    password: people_and_organizations-database
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

