spring:
  application:
    name: People and Organizations Endpoint REST
  datasource:
    url: jdbc:postgresql://localhost:5432/people_and_organizations
    username: people_and_organizations
    password: people_and_organizations
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql
#  jackson:
#    deserialization:
#      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

logging:
  level:
    ROOT: INFO
    org.springframework.data.repository: INFO
    org.hibernate: INFO


