spring:
  application:
    name: people_and_organizations-endpoint-rest
  config:
    import: "configserver:http://root:s3cr3t@localhost:8888"

logging:
  level:
    ROOT: INFO
    org:
      springframework:
        cloud: debug

