spring:
  application:
    name: People and Organizations Endpoint REST Behavior Test
  jackson:
    # Date format string or a fully-qualified date format class name. For instance, 'yyyy-MM-dd HH:mm:ss'
    date-format: "yyyy-MM-dd'T'HH:mm:ssZ"
    # Locale used for formatting
#    time-zone: "GMT+8"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/people_and_organizations
    username: people_and_organizations
    password: people_and_organizations

logging:
  level:
    ROOT: INFO
    org.springframework.data.repository: INFO
    org.springframework.web: INFO
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
