spring:
  application:
    name: People and Organizations Endpoint REST Behavior Test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/people_and_organizations
    username: people_and_organizations
    password: people_and_organizations

logging:
  level:
    ROOT: INFO
    org:
      springframework:
        data:
          repository: INFO
        web: DEBUG
        http: DEBUG
#          converter:
#            json: DEBUG
        client:
          RestTemplate: INFO
