spring:
  application:
    name: People and Organizations Endpoint REST Behavior Test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

---

spring:
  config:
    activate:
      on-profile: integration_test
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    url: jdbc:postgresql://localhost:5432/people_and_organizations
    username: people_and_organizations
    password: people_and_organizations
    driver-class-name: org.postgresql.Driver

logging:
  level:
    ROOT: INFO
    org:
      springframework:
        web:
          client: DEBUG


---

